# pyproject.toml
[tool.black]
line-length = 100
skip-string-normalization = true
include = '\.pyi?$'
target-version = ['py39']

[tool.djlint]
indent = 2
preserve_blank_lines = false
format_css = true
format_js = true
max_line_length = 100
blank_line_after_tag = "load,extends,include,block"
close_void_tags = true
profile = "django"
max_blank_lines = 1

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newlines_before_imports = true
remove_redundant_aliases = true
combine_as_imports = true
lines_after_imports = 1

[tool.pylint]
max-line-length = 100
disable = "H014" 